title: Lerntagebuch Antonia 
author: Antonia
email: antonia.stadler@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch Antonia im Modul "Bibliotheks- & Archivinformatik" - HS21

# social links

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
